# Generated by Django 5.2.14 on 2026-05-15 18:15

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='ObjectIdSequence',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('next_numeric', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Счётчик ID объектов',
                'verbose_name_plural': 'Счётчик ID объектов',
            },
        ),
        migrations.CreateModel(
            name='CatalogObject',
            fields=[
                ('code', models.CharField(editable=False, max_length=4, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255, verbose_name='От')),
                ('obj_type', models.CharField(choices=[('painting', 'Картина'), ('sculpture', 'Скульптура'), ('souvenir', 'Сувенир'), ('porcelain', 'Фарфор'), ('clock', 'Часы'), ('book', 'Книга'), ('panel', 'Панно'), ('dishes', 'Посуда'), ('carpets', 'Ковры'), ('other', 'Другое')], max_length=32, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('placement', models.TextField(blank=True, verbose_name='Размещение')),
                ('condition', models.CharField(choices=[('active', 'Норма'), ('lost', 'Утерян'), ('broken', 'Сломан'), ('written_off', 'Списан')], default='active', max_length=24, verbose_name='Состояние учёта')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('deleted', 'Удалён')], db_index=True, default='active', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects_created', to=settings.AUTH_USER_MODEL, verbose_name='Кем добавлен')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалён')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects_updated', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменён')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='PdfAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('catalog_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='catalog.catalogobject')),
            ],
            options={
                'verbose_name': 'PDF объекта',
                'verbose_name_plural': 'PDF объектов',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='PhotoAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_original', models.CharField(max_length=500, verbose_name='Оригинал (относит. путь)')),
                ('path_preview', models.CharField(blank=True, max_length=500, verbose_name='Превью')),
                ('original_name', models.CharField(max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('size', models.PositiveIntegerField(default=0)),
                ('catalog_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.catalogobject')),
            ],
            options={
                'verbose_name': 'Фото объекта',
                'verbose_name_plural': 'Фото объектов',
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PlacementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_text', models.TextField(verbose_name='Размещение (снимок)')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_history', to='catalog.catalogobject')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История размещения',
                'verbose_name_plural': 'История размещения',
                'ordering': ('-changed_at',),
            },
        ),
        migrations.AddIndex(
            model_name='catalogobject',
            index=models.Index(fields=['obj_type'], name='catalog_cat_obj_typ_6929d1_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogobject',
            index=models.Index(fields=['status'], name='catalog_cat_status_1f5dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogobject',
            index=models.Index(fields=['condition'], name='catalog_cat_conditi_23c09a_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogobject',
            index=django.contrib.postgres.indexes.GinIndex(fields=['sender'], name='catalog_obj_sender_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='catalogobject',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='catalog_obj_descr_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='catalogobject',
            index=django.contrib.postgres.indexes.GinIndex(fields=['comment'], name='catalog_obj_comment_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='catalogobject',
            index=django.contrib.postgres.indexes.GinIndex(fields=['placement'], name='catalog_obj_place_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
